// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: PowerPico

#ifndef UI_PDFIXEDPAGE_H
#define UI_PDFIXEDPAGE_H

#ifdef __cplusplus
extern "C" {
#endif



// SCREEN: ui_PDFixedPage
extern lv_obj_t * ui_PDFixedPage;

void ui_PDFixedPage_screen_init(void);
void ui_PDFixedPage_screen_destroy(void);

void ui_pdfixed_page_key_handler(void* key_event);

// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

