// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: PowerPico

#ifndef UI_PDFIXEDPAGE_H
#define UI_PDFIXEDPAGE_H

#ifdef __cplusplus
extern "C" {
#endif



// SCREEN: ui_PDFixedPage
extern void ui_PDFixedPage_screen_init(void);
extern void ui_PDFixedPage_screen_destroy(void);

// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

