// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: PowerPico

#include "../ui.h"

lv_obj_t * ui_PDFixedPage = NULL;
static lv_obj_t * ui_PanelPDVol = NULL;
static lv_obj_t * ui_LabelPDVol = NULL;
static lv_obj_t * ui_LabelPDVolUnit = NULL;
static lv_obj_t * ui_PanelPDCur = NULL;
static lv_obj_t * ui_LabelPDCur = NULL;
static lv_obj_t * ui_LabelPDCurUnit = NULL;
static lv_obj_t * ui_Spinner2 = NULL;
static lv_obj_t * ui_BtnPDSet1 = NULL;
static lv_obj_t * ui_LabelPDSet1 = NULL;
static lv_obj_t * ui_BtnPDSet2 = NULL;
static lv_obj_t * ui_LabelPDSet2 = NULL;
static lv_obj_t * ui_BtnPDSet3 = NULL;
static lv_obj_t * ui_LabelPDSet3 = NULL;
static lv_obj_t * ui_BtnPDSet4 = NULL;
static lv_obj_t * ui_LabelPDSet4 = NULL;
static lv_obj_t * ui_BtnPDSet5 = NULL;
static lv_obj_t * ui_LabelPDSet5 = NULL;
static lv_obj_t * ui_BtnPDClose = NULL;
static lv_obj_t * ui_LabelPDClose = NULL;
// event funtions

// build funtions

void ui_PDFixedPage_screen_init(void)
{
    ui_PDFixedPage = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_PDFixedPage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelPDVol = lv_obj_create(ui_PDFixedPage);
    lv_obj_set_width(ui_PanelPDVol, 80);
    lv_obj_set_height(ui_PanelPDVol, 35);
    lv_obj_set_x(ui_PanelPDVol, -30);
    lv_obj_set_y(ui_PanelPDVol, 10);
    lv_obj_set_align(ui_PanelPDVol, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_PanelPDVol, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelPDVol, lv_color_hex(0xE36666), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelPDVol, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPDVol = lv_label_create(ui_PanelPDVol);
    lv_obj_set_width(ui_LabelPDVol, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPDVol, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPDVol, -12);
    lv_obj_set_y(ui_LabelPDVol, 0);
    lv_obj_set_align(ui_LabelPDVol, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LabelPDVol, "5.42");
    lv_obj_set_style_text_font(ui_LabelPDVol, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPDVolUnit = lv_label_create(ui_PanelPDVol);
    lv_obj_set_width(ui_LabelPDVolUnit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPDVolUnit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPDVolUnit, 5);
    lv_obj_set_y(ui_LabelPDVolUnit, 0);
    lv_obj_set_align(ui_LabelPDVolUnit, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LabelPDVolUnit, "V");
    lv_obj_set_style_text_font(ui_LabelPDVolUnit, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelPDCur = lv_obj_create(ui_PDFixedPage);
    lv_obj_set_width(ui_PanelPDCur, 80);
    lv_obj_set_height(ui_PanelPDCur, 35);
    lv_obj_set_x(ui_PanelPDCur, 60);
    lv_obj_set_y(ui_PanelPDCur, 10);
    lv_obj_set_align(ui_PanelPDCur, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_PanelPDCur, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelPDCur, lv_color_hex(0x42AA49), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelPDCur, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPDCur = lv_label_create(ui_PanelPDCur);
    lv_obj_set_width(ui_LabelPDCur, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPDCur, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPDCur, -12);
    lv_obj_set_y(ui_LabelPDCur, 0);
    lv_obj_set_align(ui_LabelPDCur, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LabelPDCur, "2.25");
    lv_obj_set_style_text_font(ui_LabelPDCur, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPDCurUnit = lv_label_create(ui_PanelPDCur);
    lv_obj_set_width(ui_LabelPDCurUnit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPDCurUnit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPDCurUnit, 5);
    lv_obj_set_y(ui_LabelPDCurUnit, 0);
    lv_obj_set_align(ui_LabelPDCurUnit, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LabelPDCurUnit, "A");
    lv_obj_set_style_text_font(ui_LabelPDCurUnit, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Spinner2 = lv_spinner_create(ui_PDFixedPage, 1000, 90);
    lv_obj_set_width(ui_Spinner2, 25);
    lv_obj_set_height(ui_Spinner2, 25);
    lv_obj_set_x(ui_Spinner2, -90);
    lv_obj_set_y(ui_Spinner2, 15);
    lv_obj_set_align(ui_Spinner2, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Spinner2, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_arc_width(ui_Spinner2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(ui_Spinner2, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_BtnPDSet1 = lv_btn_create(ui_PDFixedPage);
    lv_obj_set_width(ui_BtnPDSet1, 100);
    lv_obj_set_height(ui_BtnPDSet1, 30);
    lv_obj_set_x(ui_BtnPDSet1, -55);
    lv_obj_set_y(ui_BtnPDSet1, -45);
    lv_obj_set_align(ui_BtnPDSet1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnPDSet1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnPDSet1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_BtnPDSet1, lv_color_hex(0xF40F0F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BtnPDSet1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BtnPDSet1, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPDSet1 = lv_label_create(ui_BtnPDSet1);
    lv_obj_set_width(ui_LabelPDSet1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPDSet1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelPDSet1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPDSet1, "5V  1A");
    lv_obj_set_style_text_font(ui_LabelPDSet1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnPDSet2 = lv_btn_create(ui_PDFixedPage);
    lv_obj_set_width(ui_BtnPDSet2, 100);
    lv_obj_set_height(ui_BtnPDSet2, 30);
    lv_obj_set_x(ui_BtnPDSet2, 55);
    lv_obj_set_y(ui_BtnPDSet2, -45);
    lv_obj_set_align(ui_BtnPDSet2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnPDSet2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnPDSet2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelPDSet2 = lv_label_create(ui_BtnPDSet2);
    lv_obj_set_width(ui_LabelPDSet2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPDSet2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelPDSet2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPDSet2, "9V  1A");
    lv_obj_set_style_text_font(ui_LabelPDSet2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnPDSet3 = lv_btn_create(ui_PDFixedPage);
    lv_obj_set_width(ui_BtnPDSet3, 100);
    lv_obj_set_height(ui_BtnPDSet3, 30);
    lv_obj_set_x(ui_BtnPDSet3, -55);
    lv_obj_set_y(ui_BtnPDSet3, -5);
    lv_obj_set_align(ui_BtnPDSet3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnPDSet3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnPDSet3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelPDSet3 = lv_label_create(ui_BtnPDSet3);
    lv_obj_set_width(ui_LabelPDSet3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPDSet3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelPDSet3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPDSet3, "12V  1A");
    lv_obj_set_style_text_font(ui_LabelPDSet3, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnPDSet4 = lv_btn_create(ui_PDFixedPage);
    lv_obj_set_width(ui_BtnPDSet4, 100);
    lv_obj_set_height(ui_BtnPDSet4, 30);
    lv_obj_set_x(ui_BtnPDSet4, 55);
    lv_obj_set_y(ui_BtnPDSet4, -5);
    lv_obj_set_align(ui_BtnPDSet4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnPDSet4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnPDSet4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelPDSet4 = lv_label_create(ui_BtnPDSet4);
    lv_obj_set_width(ui_LabelPDSet4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPDSet4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelPDSet4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPDSet4, "15V  1A");
    lv_obj_set_style_text_font(ui_LabelPDSet4, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnPDSet5 = lv_btn_create(ui_PDFixedPage);
    lv_obj_set_width(ui_BtnPDSet5, 100);
    lv_obj_set_height(ui_BtnPDSet5, 30);
    lv_obj_set_x(ui_BtnPDSet5, -55);
    lv_obj_set_y(ui_BtnPDSet5, 35);
    lv_obj_set_align(ui_BtnPDSet5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnPDSet5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnPDSet5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelPDSet5 = lv_label_create(ui_BtnPDSet5);
    lv_obj_set_width(ui_LabelPDSet5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPDSet5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelPDSet5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPDSet5, "20V  1A");
    lv_obj_set_style_text_font(ui_LabelPDSet5, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnPDClose = lv_btn_create(ui_PDFixedPage);
    lv_obj_set_width(ui_BtnPDClose, 210);
    lv_obj_set_height(ui_BtnPDClose, 30);
    lv_obj_set_x(ui_BtnPDClose, 0);
    lv_obj_set_y(ui_BtnPDClose, 85);
    lv_obj_set_align(ui_BtnPDClose, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnPDClose, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnPDClose, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnPDClose, lv_color_hex(0x725C08), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnPDClose, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPDClose = lv_label_create(ui_BtnPDClose);
    lv_obj_set_width(ui_LabelPDClose, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPDClose, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelPDClose, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPDClose, _("press here to close PD"));
    lv_obj_set_style_text_font(ui_LabelPDClose, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_PDFixedPage_screen_destroy(void)
{
    if(ui_PDFixedPage) lv_obj_del(ui_PDFixedPage);

    // NULL screen variables
    ui_PDFixedPage = NULL;
    ui_PanelPDVol = NULL;
    ui_LabelPDVol = NULL;
    ui_LabelPDVolUnit = NULL;
    ui_PanelPDCur = NULL;
    ui_LabelPDCur = NULL;
    ui_LabelPDCurUnit = NULL;
    ui_Spinner2 = NULL;
    ui_BtnPDSet1 = NULL;
    ui_LabelPDSet1 = NULL;
    ui_BtnPDSet2 = NULL;
    ui_LabelPDSet2 = NULL;
    ui_BtnPDSet3 = NULL;
    ui_LabelPDSet3 = NULL;
    ui_BtnPDSet4 = NULL;
    ui_LabelPDSet4 = NULL;
    ui_BtnPDSet5 = NULL;
    ui_LabelPDSet5 = NULL;
    ui_BtnPDClose = NULL;
    ui_LabelPDClose = NULL;

}
